// src/models/cuisineType.ts

export enum CuisineType {
  Asian = "Asian",
  European = "European",
  American = "American",
  MiddleEastern = "Middle Eastern",
  Mediterranean = "Mediterranean",

  Italian = "Italian",
  Chinese = "Chinese",
  Indian = "Indian",
  Mexican = "Mexican",
  French = "French",
  Japanese = "Japanese",
  Thai = "Thai",
  Spanish = "Spanish",
  Greek = "Greek",
  Turkish = "Turkish",
  Lebanese = "Lebanese",
  Korean = "Korean",
  Vietnamese = "Vietnamese",
  Moroccan = "Moroccan",
  Brazilian = "Brazilian",
  Egyptian = "Egyptian",
  Ethiopian = "Ethiopian",
  German = "German",
  Hungarian = "Hungarian",
  Indonesian = "Indonesian",
  Irish = "Irish",
  Jamaican = "Jamaican",
  Kenyan = "Kenyan",
  Malaysian = "Malaysian",
  Nigerian = "Nigerian",
  Pakistani = "Pakistani",
  Peruvian = "Peruvian",
  Polish = "Polish",
  Portuguese = "Portuguese",
  Canadian = "Canadian",
  Russian = "Russian",
  Scottish = "Scottish",
  SouthAfrican = "South African",
  Swedish = "Swedish",
  Phillipino = "Phillipino",
}

export enum CuisineCategory {
  Breakfast = "Breakfast",
  Lunch = "Lunch",
  Diner = "Diner",
  Dessert = "Dessert",
}
